#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use JSON;
use C4::Auth qw/check_api_auth/;

use C4::Context;
use UB::UBCardnum;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $cardnumber = UB::UBCardnum::create_cardnum();

print $query->header(-type => 'text/json',-charset => 'utf-8');
print encode_json({cardnumber => $cardnumber});

